### PR TITLE
Create EmojiButton.test.tsx EmojiButton unit testcase

### PR DESCRIPTION
**Pull request by GaurangMapuskar**
#### Description

Please include a brief summary of the change and include the relevant issue(s).

Closes #(issue)

#### What change does this PR introduce?

Please select the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ✔️] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

Please give a short overview/explanation on the approach taken to resolve the issue(s).

#### Checklist:

- [ ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Comment by tjtanjin** [comment]
Hey @GaurangMapuskar, thank you for the PR. However, as I've referenced above, this issue was actually assigned to another developer. With that said, I've left a comment on the issue to check in with the developer to work out how best to proceed. Will keep you posted!

Note: If you are keen to work on other issues as well, do leave a comment indicating interest to avoid potential conflicts.

**Comment by tjtanjin** [comment]
Just to update, we will be proceeding with this PR and I'll look at it properly later tonight 🙂

**Comment by heinthetaung-dev** [comment]
@tjtanjin 
@GaurangMapuskar

I just checked out the branch and ran the test. It is not working.

The steps I did.

```bash
git clone https://github.com/GaurangMapuskar/react-chatbotify.git
cd react-chatbotify
npm install
npm run unit:test
```

This is the output.

```bash
> react-chatbotify@2.0.0-beta.15 unit:test
> jest __tests__/

(node:70674) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 FAIL  __tests__/components/buttons/EmojiButton.test.tsx
  ● Test suite failed to run

    __tests__/components/buttons/EmojiButton.test.tsx:5:25 - error TS2307: Cannot find module './EmojiButton' or its corresponding type declarations.

    5 import EmojiButton from "./EmojiButton";
                              ~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:6:36 - error TS2307: Cannot find module '../../../context/SettingsContext' or its corresponding type declarations.

    6 import { useSettingsContext } from "../../../context/SettingsContext";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:7:34 - error TS2307: Cannot find module '../../../context/StylesContext' or its corresponding type declarations.

    7 import { useStylesContext } from "../../../context/StylesContext";
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:8:35 - error TS2307: Cannot find module '../../../context/BotRefsContext' or its corresponding type declarations.

    8 import { useBotRefsContext } from "../../../context/BotRefsContext";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:9:37 - error TS2307: Cannot find module '../../../hooks/internal/useTextAreaInternal' or its corresponding type declarations.

    9 import { useTextAreaInternal } from "../../../hooks/internal/useTextAreaInternal";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:53:25 - error TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.

    53     expect(emojiButton).toBeInTheDocument();
                               ~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:60:24 - error TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLDivElement | null>'.

    60     expect(emojiPopup).toBeInTheDocument();
                              ~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:81:36 - error TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.

    81     expect(screen.getByText("😀")).toBeInTheDocument();
                                          ~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:87:42 - error TS2339: Property 'toBeInTheDocument' does not exist on type 'Matchers<void, HTMLElement | null>'.

    87     expect(screen.queryByText("😀")).not.toBeInTheDocument();
                                                ~~~~~~~~~~~~~~~~~
    __tests__/components/buttons/EmojiButton.test.tsx:103:42 - error TS2339: Property 'toBeInTheDocument' does not exist on type 'Matchers<void, HTMLElement | null>'.

    103     expect(screen.queryByText("😀")).not.toBeInTheDocument();
                                                 ~~~~~~~~~~~~~~~~~

(node:70670) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/hooks/internal/useChatWindowInternal.test.ts (5.762 s)
(node:70675) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/hooks/internal/useNotificationsInternal.test.ts (5.791 s)
(node:70671) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/hooks/internal/useVoiceInternal.test.ts (5.777 s)
 PASS  __tests__/hooks/internal/useAudioInternal.test.ts
(node:70672) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/components/buttons/NotificationButton.test.tsx (5.851 s)
(node:70673) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/components/buttons/AudioButton.test.tsx (5.899 s)
(node:70669) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/hooks/internal/useChatHistoryInternal.test.ts (5.963 s)
 PASS  __tests__/hooks/internal/userBotIdInternal.test.ts
 PASS  __tests__/hooks/internal/useFirstInteractionInternal.test.ts

Test Suites: 1 failed, 9 passed, 10 total
Tests:       22 passed, 22 total
Snapshots:   0 total
Time:        6.621 s
Ran all test suites matching /__tests__\//i.
`

**Comment by tjtanjin** [comment]
Thank you for checking @heinthetaung-dev 😊 @GaurangMapuskar, are you able to resolve the errors? There're quite a fair bit of areas that require changes such as wrong imports. Do feel free to reach out if you need assistance.

**Comment by tjtanjin** [comment]
Hey @GaurangMapuskar, please don't mind the rush, but if you're unable to work on this issue do let us know soon 🥺

**Pull request closed without merging**
