### PR TITLE
test: add unit tests for ToastsContext

### LINKED ISSUE #233: [Task] Add unit test cases for ToastsContext
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ToastsContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `ToastsContext`.

**Additional Context:**
- The `ToastsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/ToastsContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

### PR DESCRIPTION
**Pull request by Goketech**
#### Description

This Pull requests introduces unit testing for ToastsContext.

Closes #233 

#### What change does this PR introduce?

Please select the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

The proposed approach involves writing unit tests for ToastContext. The tests use render from the React testing library to test the toast context and behavior.

#### Checklist:

- [x] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Testing has been done for the change(s) added (for bug fixes/features)
- [x] Relevant comments/docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Review by tjtanjin — CHANGES_REQUESTED** [review]
Hey @Goketech, there are lint errors to be resolved 😞

**Comment by Goketech** [comment]
> Hey @Goketech, there are lint errors to be resolved 😞

Hi @tjtanjin,

I've resolved the lint error.
I noticed the workflow failed due to unit tests and these tests passed locally.

Could you take a look or re-run the job. 😔

**Comment by tjtanjin** [comment]
> > Hey @Goketech, there are lint errors to be resolved 😞
> 
> 
> 
> Hi @tjtanjin,
> 
> 
> 
> I've resolved the lint error.
> 
> I noticed the workflow failed due to unit tests and these tests passed locally.
> 
> 
> 
> Could you take a look or re-run the job. 😔

Hey @Goketech, the unit test failure isn't an issue on your end. Try merging the main branch 😃

**Review by tjtanjin — APPROVED** [review]
LGTM! 😊

**Pull request merged**
