### PR TITLE
Added unit testcases for useToastsInternal

### LINKED ISSUE #130: [Task] Add unit test cases for useToastsInternal hook
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `useToastsInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `useToastsInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

### PR DESCRIPTION
**Pull request by anjumnnit**
Closes #130 

Please select the relevant option(s).

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### Checklist:

- [x] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Testing has been done for the change(s) added (for bug fixes/features)
- [x] Relevant comments/docs have been added/updated (for bug fixes/features)

I would really appreciate if you review my  PR as hacktoberfest'24 is coming to an end.

### CODE REVIEW

**Comment by anjumnnit** [comment]
@tjtanjin  It's my last PR you helped me a lot for my other PR's kindly review this PR too so that I can complete the hacktoberfest'24 Challenge :)

**Review by tjtanjin — CHANGES_REQUESTED** [review]
Hey @anjumnnit, there're warnings raised by the Lint stage for the use of the `any` type 🥹

**Comment by anjumnnit** [comment]
> Hey @anjumnnit, there're warnings raised by the Lint stage for the use of the `any` type 🥹

you can review now....😢

**Review by tjtanjin — APPROVED** [review]
LGTM!

**Comment by anjumnnit** [comment]
> LGTM
Tysmmm😭.....I really liked your project love to contribute more and connect with you.

**Pull request merged**
