### PR TITLE
test: adding unit tests for buttonBuilder

### LINKED ISSUE #194: [Task] Add unit test cases for buttonBuilder utils
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `buttonBuilder` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `buttonBuilder`.

**Additional Context:**
- The `buttonBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/buttonBuilder.tsx)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

### PR DESCRIPTION
**Pull request by Nandinibajaj16**
#### Description

Please include a brief summary of the change and include the relevant issue(s).

Closes #194 

#### What change does this PR introduce?

Please select the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

Please give a short overview/explanation on the approach taken to resolve the issue(s).

#### Checklist:

- [ ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Comment by Nandinibajaj16** [comment]
@tjtanjin can you help here why the build is failing?

**Comment by tjtanjin** [comment]
> @tjtanjin can you help here why the build is failing?

Hey @Nandinibajaj16, it's not your issue haha 😅 Try merging into master.

**Comment by Nandinibajaj16** [comment]
@tjtanjin can you review now, this would be my last PR for hacktober, thanks.

**Review by tjtanjin — APPROVED** [review]
LGTM! 😊

**Pull request merged**
