### PR TITLE
test: Adding Cypress integration testcase for Sensitive input

### PR DESCRIPTION
**Pull request by arulk8**
#### Description

Please include a brief summary of the change and include the relevant issue(s).

Closes #(issue)

#### What change does this PR introduce?

Please select the relevant option(s).

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

Please give a short overview/explanation on the approach taken to resolve the issue(s).

#### Checklist:

- [ ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

Images:
1.  sensitive text 
image
image

2. Markup language
image

### CODE REVIEW

**Review by tjtanjin — APPROVED** [review]
LGTM! On a side note, the current integration test approach is not sustainable, reason being we're only relying on a single configuration of settings for testing. Ideally, we should have multiple instances of the chatbot with different configurations to cover more grounds (e.g. markup language **should not work** if `dangerouslySetInnerHtml` is false). That's an issue for another time though, thanks for working on this 😊

**Comment by arulk8** [comment]
> LGTM! On a side note, the current integration test approach is not sustainable, reason being we're only relying on a single configuration of settings for testing. Ideally, we should have multiple instances of the chatbot with different configurations to cover more grounds (e.g. markup language **should not work** if `dangerouslySetInnerHtml` is false). That's an issue for another time though, thanks for working on this 😊

I agree! , I also had this thought. I was not able to figure out a approach to pass different configurations. using state to load different configuration is one way.

**Comment by tjtanjin** [comment]
> > LGTM! On a side note, the current integration test approach is not sustainable, reason being we're only relying on a single configuration of settings for testing. Ideally, we should have multiple instances of the chatbot with different configurations to cover more grounds (e.g. markup language **should not work** if `dangerouslySetInnerHtml` is false). That's an issue for another time though, thanks for working on this 😊
> 
> 
> 
> I agree! , I also had this thought. I was not able to figure out a approach to pass different configurations. using state to load different configuration is one way.

This can likely be broken down into a few issues:
- Create toggle buttons to switch between different chatbot configurations
- Create issue for different chatbot configurations (can be 1 issue per config e.g. all settings enabled, all settings disabled etc)

This is not pressing but if you are keen, we can talk more on discord 🙂

**Comment by arulk8** [comment]
> > > LGTM! On a side note, the current integration test approach is not sustainable, reason being we're only relying on a single configuration of settings for testing. Ideally, we should have multiple instances of the chatbot with different configurations to cover more grounds (e.g. markup language **should not work** if `dangerouslySetInnerHtml` is false). That's an issue for another time though, thanks for working on this 😊
> > 
> > 
> > I agree! , I also had this thought. I was not able to figure out a approach to pass different configurations. using state to load different configuration is one way.
> 
> This can likely be broken down into a few issues:
> 
> * Create toggle buttons to switch between different chatbot configurations
> * Create issue for different chatbot configurations (can be 1 issue per config e.g. all settings enabled, all settings disabled etc)
> 
> This is not pressing but if you are keen, we can talk more on discord 🙂

Yes we can do that.

**Pull request merged**
