### PR TITLE
Svg size reduced

### LINKED ISSUE #21: [Task] Compress/resize the image/audio assets to an appropriate size to reduce build package size
**Description:**
Currently, in v1.5.1, the build size is around 1.7mb. This is an improvement from previous versions where the build size goes up to 4mb (yikes!). Moving forward, there is room to further reduce the build package size by compressing/resizing the image/audio assets. Some of them are still larger than they need to be.

**Note:**
- Pull requests should be opened to the branch `working-branch-2.0.0` instead of `master`

### PR DESCRIPTION
**Pull request by sharabhh**
#### Description

reduced svgs file size for : -

(these files are in src/assets)

voice_icon from 10.26kb to 7.30kb
chat_icon from 24.53kb to 16.13kb
audio_icon from 5.30kb to 3.96kb
file_attachment_icon from 4.13kb to 3.08kb
notification_icon from 4.61kb to 3.49kb

I wasn't able to compress WAV file

Closes #21 

Please select the relevant option(s).

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

used an online compressor to reduce file sizes as much was possible to reduce package size

#### Checklist:

- [ ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Comment by sharabhh** [comment]
I'll fix this one, I accidentally linked it with #27 rather than #21

**Comment by sharabhh** [comment]
Packages got updated by themselves, i didn't notice it. I'll fix it

**Comment by tjtanjin** [comment]
> Packages got updated by themselves, i didn't notice it. I'll fix it

Hey! Thank you for taking time to look at this. You'll want to branch out from the latest commit on master in your new PR.

**Comment by sharabhh** [comment]
> > Packages got updated by themselves, i didn't notice it. I'll fix it
> 
> Hey! Thank you for taking time to look at this. You'll want to branch out from the latest commit on master in your new PR (feel free to merge into Master, this doesn't necessarily need to wait for v2.0.0)

oh okay, I'll make a pr for master only then

**Pull request closed without merging**
