### PR TITLE
Added testcases for BotStatesContext 

### LINKED ISSUE #227: [Task] Add unit test cases for BotStatesContext
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `BotStatesContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `BotStatesContext`.

**Additional Context:**
- The `BotStatesContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/BotStatesContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

### PR DESCRIPTION
**Pull request by Suvrat1629**
#### Description

Please include a brief summary of the change and include the relevant issue(s).

Closes #227

#### What change does this PR introduce?
I have added testcases for BotStatesContext.

Please select the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

Please give a short overview/explanation on the approach taken to resolve the issue(s).
I have created the BotStatesContext.test.tsx file which has test cases for the BotStatesContext.

#### Checklist:

- [x] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Review by tjtanjin — CHANGES_REQUESTED** [review]
Hey @Suvrat1629, this PR contains the exact same issues as the StylesContext PR (e.g. extra viteconfig file, deprecated library additions). It might help to clean up your branch first.

**Comment by Suvrat1629** [comment]
ok i will work on that

**Comment by Suvrat1629** [comment]
I have made the necessary changes please review it

**Comment by Suvrat1629** [comment]
@tjtanjin updates?

**Review by tjtanjin — CHANGES_REQUESTED** [review]
Merge conflicts from the StylesContext file - this PR is only for BotStatesContext.

**Comment by Suvrat1629** [comment]
Ok I will close this pr and open a new pr for this issue again

**Comment by Suvrat1629** [comment]
Ok I have resolved the conflicts

**Review by tjtanjin — CHANGES_REQUESTED** [review]
Hey, just one last change - `package.json` and `package-lock.json` shouldn't be included here. There are no changes required of them. Good to merge after removing them, thanks!

**Comment by Suvrat1629** [comment]
I dont understand what exactly you want me to do. Do you want me to remove and add the package.json and package-lock.json all over again?

**Comment by tjtanjin** [comment]
> I dont understand what exactly you want me to do. Do you want me to remove and add the package.json and package-lock.json all over again? Cauz I am not able to see any conflicts so i opened the pr

There are no conflicts, but there are also no changes required to `package.json` and package-lock.json`. This PR only requires a single file that is the `BotStatesContext.test.ts`. Hope this clarifies!

**Comment by Suvrat1629** [comment]
Ok i will open a new pr for this then

**Pull request closed without merging**
